// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypgrvvloxoklktftfjze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZ3J2dmxveG9rbGt0ZnRmanplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDc3MTEsImV4cCI6MjA2NTUyMzcxMX0.LIWKlobiCb_rgz32VWkZU6uJMjpR98t9HgNkisQcMZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);